version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  build-and-test:
    jobs:
      - build-and-test
