version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: install
          command: yarn install
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - run:
          name: release
          command: yarn run semantic-release || true

workflows:
  build-and-test:
    jobs:
      - build-and-test
